Repository acheong08/EdgeGPT, pull requests merged in 2023-05, with the labels that each got.

#361 Copy ISSUE_TEMPLATE from ChatGPT
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: triage-needed

#360 Create conversation asynchronously
  docs/README.md
  docs/README_es.md
  docs/README_ja.md
  docs/README_zh-cn.md
  src/EdgeGPT.py
Labels: triage-needed

#362 Anti message revoke
  src/EdgeGPT.py
Labels: triage-needed

#363 Add "web page context"
  src/EdgeGPT.py
Labels: enhancement

#369 Feature search results
  docs/wiki/EdgeGPT.md
  src/EdgeGPT.py
Labels: triage-needed

#370 fix Expected type Mismatch
  src/EdgeGPT.py
Labels: bugfix

#382 [Bug]: Can't create image.
  src/EdgeGPT.py
Labels: bugfix

#381 Use my own project to label
  .github/tagger-pr.json
  .github/tagger.json
  .github/workflows/issues.yml
  .github/workflows/pull-request.yml
Labels: triage-needed

#375 spellings of Traditional Chinese readme
  docs/README_zh-tw.md
Labels: triage-needed

#384 GET Request retries
  src/EdgeGPT.py
Labels: triage-needed

#391 fix #390
  src/EdgeGPT.py
Labels: bugfix

#396 New Query, ImageQuery, and Cookie helper classes; Updated README to explain capabilities
  docs/README.md
  src/EdgeGPT.py
Labels: triage-needed
